### ISSUE TITLE
Loading text

### ISSUE THREAD

**Issue by dumdum310** [KirillMcQ/SegFaultersFeedback#7]
When I click the SegFaulters logo on the top-left, a "loading" screen pops up for a split second, before taking me to the questions tab. (read the rest) 

Loading text does not go from: "Loading..." => "Loading.." (peep the periods)

The loading text instead just goes on screen as is: "Loading...Loading.." (They both show on screen)

**Comment by dumdum310** [comment]
#bug

**Comment by KirillMcQ** [comment]
Not a bug, it loads two separate things.

Do you think this should be changed though?
